name: Open MR Deployment Checks
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - main

jobs:
  Code-Quality-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
      
      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Unit Tests
        run: npm run test

      - name: Type Check
        run: npm run type-check

  Docker-Build-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LOCAL_DATABASE_URL: ${{ secrets.LOCAL_DATABASE_URL }}
        run: |
          docker build --no-cache \
            --build-arg DATABASE_URL="$DATABASE_URL" \
            --build-arg LOCAL_DATABASE_URL="$LOCAL_DATABASE_URL" \
            -t its:latest .
